### ISSUE TITLE
Commit "delivery tracking" 📦🚚

### ISSUE THREAD

**Issue by cben** [cben/plan#26]
If you think of upstream commits as "gifts", you might be impatient and want to know how they're progressing towards being widely available, in the style of package-tracking sites :package: :truck: 

- [ ] upstream MR merged (per branch)
- [ ] upstream release tagged
- [ ] uploaded to various language managers like npm, PyPI, etc.
- [ ] snap, flathub, AppImage
- [ ] docker image
- [ ] Linux distributions picking it up (per distro per version)
  - [ ] required dependencies picked up by the distro

**Comment by cben** [comment]
Surely the needed mechanisms alseady exist within vulnerability tracking tools.  Shrug.
